language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '14'
git:
  depth: 3
script:
  - yarn test
notifications:
  email:
    recipients:
      - cajita2002@outlook.es
    on_success: always
    on_failure: always
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: a6434fbc-0d8a-4fda-88b3-2900d9a5bc3e
  app: slysux-platzi-store-backend
  on:
    repo: Slysux/platzi-store-backend